# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class ContainersBody(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, threshold: float=None):  # noqa: E501
        """ContainersBody - a model defined in Swagger

        :param threshold: The threshold of this ContainersBody.  # noqa: E501
        :type threshold: float
        """
        self.swagger_types = {
            'threshold': float
        }

        self.attribute_map = {
            'threshold': 'threshold'
        }
        self._threshold = threshold

    @classmethod
    def from_dict(cls, dikt) -> 'ContainersBody':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The containers_body of this ContainersBody.  # noqa: E501
        :rtype: ContainersBody
        """
        return util.deserialize_model(dikt, cls)

    @property
    def threshold(self) -> float:
        """Gets the threshold of this ContainersBody.


        :return: The threshold of this ContainersBody.
        :rtype: float
        """
        return self._threshold

    @threshold.setter
    def threshold(self, threshold: float):
        """Sets the threshold of this ContainersBody.


        :param threshold: The threshold of this ContainersBody.
        :type threshold: float
        """

        self._threshold = threshold
