# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class CorrectResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, command: str=None, content: object=None):  # noqa: E501
        """CorrectResponse - a model defined in Swagger

        :param command: The command of this CorrectResponse.  # noqa: E501
        :type command: str
        :param content: The content of this CorrectResponse.  # noqa: E501
        :type content: object
        """
        self.swagger_types = {
            'command': str,
            'content': object
        }

        self.attribute_map = {
            'command': 'command',
            'content': 'content'
        }
        self._command = command
        self._content = content

    @classmethod
    def from_dict(cls, dikt) -> 'CorrectResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The CorrectResponse of this CorrectResponse.  # noqa: E501
        :rtype: CorrectResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def command(self) -> str:
        """Gets the command of this CorrectResponse.

        type of results: ok or error  # noqa: E501

        :return: The command of this CorrectResponse.
        :rtype: str
        """
        return self._command

    @command.setter
    def command(self, command: str):
        """Sets the command of this CorrectResponse.

        type of results: ok or error  # noqa: E501

        :param command: The command of this CorrectResponse.
        :type command: str
        """

        self._command = command

    @property
    def content(self) -> object:
        """Gets the content of this CorrectResponse.

        Brief description of the operation result  # noqa: E501

        :return: The content of this CorrectResponse.
        :rtype: object
        """
        return self._content

    @content.setter
    def content(self, content: object):
        """Sets the content of this CorrectResponse.

        Brief description of the operation result  # noqa: E501

        :param content: The content of this CorrectResponse.
        :type content: object
        """

        self._content = content
