# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class ContainersAddressBody1(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, threshold: int=None):  # noqa: E501
        """ContainersAddressBody1 - a model defined in Swagger

        :param threshold: The threshold of this ContainersAddressBody1.  # noqa: E501
        :type threshold: int
        """
        self.swagger_types = {
            'threshold': int
        }

        self.attribute_map = {
            'threshold': 'threshold'
        }
        self._threshold = threshold

    @classmethod
    def from_dict(cls, dikt) -> 'ContainersAddressBody1':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The containers_address_body_1 of this ContainersAddressBody1.  # noqa: E501
        :rtype: ContainersAddressBody1
        """
        return util.deserialize_model(dikt, cls)

    @property
    def threshold(self) -> int:
        """Gets the threshold of this ContainersAddressBody1.


        :return: The threshold of this ContainersAddressBody1.
        :rtype: int
        """
        return self._threshold

    @threshold.setter
    def threshold(self, threshold: int):
        """Sets the threshold of this ContainersAddressBody1.


        :param threshold: The threshold of this ContainersAddressBody1.
        :type threshold: int
        """

        self._threshold = threshold
