openapi: 3.0.0
info:
  title: Health Monitor REST API
  description: "REST API for remote control and management of the Docker Health System\
    \ by users. Allow the display of containers maintained on systems, add and remove\
    \ containers or new machines. Modify the operating parameters of the system and\
    \ launch a testing application to verify the functionality of the system"
  contact: {}
  version: 1.0.0
servers:
- url: http://172.16.3.167:80/healthmonitor
tags:
- name: containers
  description: "Docker Containers collection, permits to show and manage all the available\
    \ Linux Containers"
- name: test
  description: "System testing functionalities, permits to start, stop and configure\
    \ a practical evaluation of the service"
paths:
  /containers:
    get:
      tags:
      - containers
      summary: Get all managed containers
      description: It gives a list of all the Docker hosts with all the allocated
        containers
      operationId: get_all_containers
      responses:
        "200":
          description: operation completed
      x-openapi-router-controller: swagger_server.controllers.containers_controller
    post:
      tags:
      - containers
      summary: Update the threshold of all the docker managers
      description: It changes the thresholds used by all the docker managers to evaluate
        the Health of the containers
      operationId: change_all_threshold
      parameters:
      - name: threshold
        in: query
        required: true
        style: form
        explode: true
        schema:
          type: number
      responses:
        "200":
          description: operation completed
      x-openapi-router-controller: swagger_server.controllers.containers_controller
  /containers/{address}:
    get:
      tags:
      - containers
      summary: Get all the containers
      description: It gives all the containers maintained by the specified host
      operationId: get_host_containers
      parameters:
      - name: address
        in: path
        description: the address of the machine which maintains the containers
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: operation completed
      x-openapi-router-controller: swagger_server.controllers.containers_controller
    put:
      tags:
      - containers
      summary: Add a new Docker host
      description: It adds a new docker host in which our service will be deployed
      operationId: add_host
      parameters:
      - name: address
        in: path
        description: the address of the machine in which put a new manager
        required: true
        style: simple
        explode: false
        schema:
          type: string
        example: 172.16.3.167
      - name: password
        in: query
        description: The password used from the root user of the destination machine
        required: true
        allowEmptyValue: true
        style: form
        explode: true
        schema:
          type: string
        example: lost
      responses:
        "200":
          description: operation completed
      x-openapi-router-controller: swagger_server.controllers.containers_controller
    post:
      tags:
      - containers
      summary: Update the threshold of the selected docker manager
      description: It changes the threshold used by the selected docker manager to
        evaluate the Health of the containers
      operationId: change_threshold
      parameters:
      - name: address
        in: path
        description: the address of the machine which maintains the manager
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: threshold
        in: query
        description: the address of the machine which maintains the manager
        required: true
        style: form
        explode: true
        schema:
          type: number
      responses:
        "200":
          description: operation completed
      x-openapi-router-controller: swagger_server.controllers.containers_controller
    delete:
      tags:
      - containers
      summary: Remove a Docker host
      description: It removes from the service management the container specified
        by the given ID. The docker host and its containers will be leaved on the
        machine in theirs current status
      operationId: remove_host
      parameters:
      - name: address
        in: path
        description: the address of the machine which maintains the manager
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: password
        in: query
        description: The password used from the root user of the destination machine
        required: true
        allowEmptyValue: true
        style: form
        explode: true
        schema:
          type: string
      responses:
        "200":
          description: operation completed
      x-openapi-router-controller: swagger_server.controllers.containers_controller
  /containers/{address}/{containerID}:
    get:
      tags:
      - containers
      summary: Get a container
      description: Returns the information about a container identified by the ip
        address of the target machine and the containerID
      operationId: get_container
      parameters:
      - name: containerID
        in: path
        description: the ID associated with the container the user want to get from
          the service
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: address
        in: path
        description: the address of the machine which maintains the container
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: operation completed
      x-openapi-router-controller: swagger_server.controllers.containers_controller
    put:
      tags:
      - containers
      summary: Add a new Docker container
      description: It adds a new docker container from the available Docker containers
        to be managed by our Health monitoring system
      operationId: add_container
      parameters:
      - name: containerID
        in: path
        description: the ID associated with the container the user want to add to
          the service
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: address
        in: path
        description: the address of the machine which maintains the container
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: operation completed
      x-openapi-router-controller: swagger_server.controllers.containers_controller
    delete:
      tags:
      - containers
      summary: Remove a container from the service
      description: It removes from the service management the container specified
        by the given ID and located into the given address. After the service removal
        the container will be leaved on the machine in its current status
      operationId: remove_container
      parameters:
      - name: containerID
        in: path
        description: the ID associated with the container the user want to remove
          from the service
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: address
        in: path
        description: the address of the machine which maintains the container
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: operation completed
      x-openapi-router-controller: swagger_server.controllers.containers_controller
  /test:
    put:
      tags:
      - test
      summary: Add all the antagonists
      description: Execute the antagonist into each machine under control of the service
      operationId: add_antagonists
      responses:
        "200":
          description: operation completed
      x-openapi-router-controller: swagger_server.controllers.test_controller
    post:
      tags:
      - test
      summary: Update the configuration used by all the antagonists
      description: It changes the configuration used by the antogonists deployed in
        each machine under the service control
      operationId: change_antagonists_config
      parameters:
      - name: heavy
        in: query
        description: "Define the impact of the antagonist on the containers. Three\
          \ possibile values: hard, medium, low"
        required: true
        style: form
        explode: true
        schema:
          type: string
      - name: balance
        in: query
        description: Define the behavior of the antagonist with a percentage which
          define the probability of performing a shutdown attack. Otherwise it will
          perform packet loss attack
        required: true
        style: form
        explode: true
        schema:
          type: number
      responses:
        "200":
          description: operation completed
      x-openapi-router-controller: swagger_server.controllers.test_controller
    delete:
      tags:
      - test
      summary: Remove all the antagonists
      description: Stops the running antagonists in each machine under the service
        control
      operationId: remove_antagonists
      parameters: []
      responses:
        "200":
          description: operation completed
      x-openapi-router-controller: swagger_server.controllers.test_controller
  /test/{address}:
    put:
      tags:
      - test
      summary: Add an antagonist
      description: It adds a new antagonist on the selected docker host
      operationId: add_host_antagonist
      parameters:
      - name: address
        in: path
        description: the IPv4 address of the destination machine
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: aggressivity
        in: query
        description: the probability(0-100%) that the antagonist will attack the containers
        required: true
        style: form
        explode: true
        schema:
          type: number
        example: 60
      - name: behaviour
        in: query
        description: the probability(0-100%) that the antagonist will shut down a
          container insted of applying a packet loss(packet loss is the remaining
          probability)
        required: true
        style: form
        explode: true
        schema:
          type: number
        example: 50
      responses:
        "200":
          description: operation completed
      x-openapi-router-controller: swagger_server.controllers.test_controller
    post:
      tags:
      - test
      summary: Update the configuration used by an antagonist
      description: It changes the configuration used by an antagonist into the defined
        docker host
      operationId: change_host_antagonist_config
      parameters:
      - name: address
        in: path
        description: the IPv4 address of the destination machine
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: heavy
        in: query
        description: "Define the impact of the antagonist on the containers. Three\
          \ possibile values: hard, medium, low"
        required: true
        style: form
        explode: true
        schema:
          type: number
      - name: balance
        in: query
        description: Define the behavior of the antagonist with a percentage which
          define the probability of performing a shutdown attack. Otherwise it will
          perform packet loss attack
        required: false
        style: form
        explode: true
        schema:
          type: number
      responses:
        "200":
          description: operation completed
      x-openapi-router-controller: swagger_server.controllers.test_controller
    delete:
      tags:
      - test
      summary: Remove an antagonist from a docker host
      description: It stops an antagonist running on the selected docker host
      operationId: remove_host_antagonist
      parameters:
      - name: address
        in: path
        description: the IPv4 address of the destination machine
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: operation completed
      x-openapi-router-controller: swagger_server.controllers.test_controller
components: {}

