# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class AllContainersResponseDescription(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, address: str=None, content: object=None):  # noqa: E501
        """AllContainersResponseDescription - a model defined in Swagger

        :param address: The address of this AllContainersResponseDescription.  # noqa: E501
        :type address: str
        :param content: The content of this AllContainersResponseDescription.  # noqa: E501
        :type content: object
        """
        self.swagger_types = {
            'address': str,
            'content': object
        }

        self.attribute_map = {
            'address': 'address',
            'content': 'content'
        }
        self._address = address
        self._content = content

    @classmethod
    def from_dict(cls, dikt) -> 'AllContainersResponseDescription':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The AllContainersResponse_description of this AllContainersResponseDescription.  # noqa: E501
        :rtype: AllContainersResponseDescription
        """
        return util.deserialize_model(dikt, cls)

    @property
    def address(self) -> str:
        """Gets the address of this AllContainersResponseDescription.

        the IPv4 address of the selected docker host  # noqa: E501

        :return: The address of this AllContainersResponseDescription.
        :rtype: str
        """
        return self._address

    @address.setter
    def address(self, address: str):
        """Sets the address of this AllContainersResponseDescription.

        the IPv4 address of the selected docker host  # noqa: E501

        :param address: The address of this AllContainersResponseDescription.
        :type address: str
        """

        self._address = address

    @property
    def content(self) -> object:
        """Gets the content of this AllContainersResponseDescription.


        :return: The content of this AllContainersResponseDescription.
        :rtype: object
        """
        return self._content

    @content.setter
    def content(self, content: object):
        """Sets the content of this AllContainersResponseDescription.


        :param content: The content of this AllContainersResponseDescription.
        :type content: object
        """

        self._content = content
