# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class CorrectMultiResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, command: str=None, content: List[object]=None):  # noqa: E501
        """CorrectMultiResponse - a model defined in Swagger

        :param command: The command of this CorrectMultiResponse.  # noqa: E501
        :type command: str
        :param content: The content of this CorrectMultiResponse.  # noqa: E501
        :type content: List[object]
        """
        self.swagger_types = {
            'command': str,
            'content': List[object]
        }

        self.attribute_map = {
            'command': 'command',
            'content': 'content'
        }
        self._command = command
        self._content = content

    @classmethod
    def from_dict(cls, dikt) -> 'CorrectMultiResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The CorrectMultiResponse of this CorrectMultiResponse.  # noqa: E501
        :rtype: CorrectMultiResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def command(self) -> str:
        """Gets the command of this CorrectMultiResponse.

        type of results: ok or error  # noqa: E501

        :return: The command of this CorrectMultiResponse.
        :rtype: str
        """
        return self._command

    @command.setter
    def command(self, command: str):
        """Sets the command of this CorrectMultiResponse.

        type of results: ok or error  # noqa: E501

        :param command: The command of this CorrectMultiResponse.
        :type command: str
        """

        self._command = command

    @property
    def content(self) -> List[object]:
        """Gets the content of this CorrectMultiResponse.


        :return: The content of this CorrectMultiResponse.
        :rtype: List[object]
        """
        return self._content

    @content.setter
    def content(self, content: List[object]):
        """Sets the content of this CorrectMultiResponse.


        :param content: The content of this CorrectMultiResponse.
        :type content: List[object]
        """

        self._content = content
