# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server.models.inline_response2001_containers import InlineResponse2001Containers
from openapi_server import util

from openapi_server.models.inline_response2001_containers import InlineResponse2001Containers  # noqa: E501

class InlineResponse2002(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, hostname=None, containers=None):  # noqa: E501
        """InlineResponse2002 - a model defined in OpenAPI

        :param hostname: The hostname of this InlineResponse2002.  # noqa: E501
        :type hostname: str
        :param containers: The containers of this InlineResponse2002.  # noqa: E501
        :type containers: List[InlineResponse2001Containers]
        """
        self.openapi_types = {
            'hostname': str,
            'containers': List[InlineResponse2001Containers]
        }

        self.attribute_map = {
            'hostname': 'hostname',
            'containers': 'containers'
        }

        self._hostname = hostname
        self._containers = containers

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse2002':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200_2 of this InlineResponse2002.  # noqa: E501
        :rtype: InlineResponse2002
        """
        return util.deserialize_model(dikt, cls)

    @property
    def hostname(self):
        """Gets the hostname of this InlineResponse2002.


        :return: The hostname of this InlineResponse2002.
        :rtype: str
        """
        return self._hostname

    @hostname.setter
    def hostname(self, hostname):
        """Sets the hostname of this InlineResponse2002.


        :param hostname: The hostname of this InlineResponse2002.
        :type hostname: str
        """

        self._hostname = hostname

    @property
    def containers(self):
        """Gets the containers of this InlineResponse2002.


        :return: The containers of this InlineResponse2002.
        :rtype: List[InlineResponse2001Containers]
        """
        return self._containers

    @containers.setter
    def containers(self, containers):
        """Sets the containers of this InlineResponse2002.


        :param containers: The containers of this InlineResponse2002.
        :type containers: List[InlineResponse2001Containers]
        """

        self._containers = containers
