# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class InlineObject(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, address=None, username=None, password=None):  # noqa: E501
        """InlineObject - a model defined in OpenAPI

        :param address: The address of this InlineObject.  # noqa: E501
        :type address: str
        :param username: The username of this InlineObject.  # noqa: E501
        :type username: str
        :param password: The password of this InlineObject.  # noqa: E501
        :type password: str
        """
        self.openapi_types = {
            'address': str,
            'username': str,
            'password': str
        }

        self.attribute_map = {
            'address': 'address',
            'username': 'username',
            'password': 'password'
        }

        self._address = address
        self._username = username
        self._password = password

    @classmethod
    def from_dict(cls, dikt) -> 'InlineObject':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_object of this InlineObject.  # noqa: E501
        :rtype: InlineObject
        """
        return util.deserialize_model(dikt, cls)

    @property
    def address(self):
        """Gets the address of this InlineObject.

        the IPv4 address of a machine  # noqa: E501

        :return: The address of this InlineObject.
        :rtype: str
        """
        return self._address

    @address.setter
    def address(self, address):
        """Sets the address of this InlineObject.

        the IPv4 address of a machine  # noqa: E501

        :param address: The address of this InlineObject.
        :type address: str
        """
        if address is None:
            raise ValueError("Invalid value for `address`, must not be `None`")  # noqa: E501

        self._address = address

    @property
    def username(self):
        """Gets the username of this InlineObject.

        the username to be used to access the machine. If missing the service will use root  # noqa: E501

        :return: The username of this InlineObject.
        :rtype: str
        """
        return self._username

    @username.setter
    def username(self, username):
        """Sets the username of this InlineObject.

        the username to be used to access the machine. If missing the service will use root  # noqa: E501

        :param username: The username of this InlineObject.
        :type username: str
        """

        self._username = username

    @property
    def password(self):
        """Gets the password of this InlineObject.

        the password to be used to access the machine. If missing the service will assume that no password is setted  # noqa: E501

        :return: The password of this InlineObject.
        :rtype: str
        """
        return self._password

    @password.setter
    def password(self, password):
        """Sets the password of this InlineObject.

        the password to be used to access the machine. If missing the service will assume that no password is setted  # noqa: E501

        :param password: The password of this InlineObject.
        :type password: str
        """

        self._password = password
